### ISSUE TITLE
cmake for MiMA v2

### ISSUE THREAD

**Issue by dorchard** [DataWaveProject/MiMA-machine-learning#1]
- [x] Works on NYU computer
- [ ] Works on Sherlock (@lm2612) 
- [x] PR to parent repo (@jatkinson1000)
- [ ] Documentation (want to be able to run alongside existing build process) (@jatkinson1000)

**Comment by jatkinson1000** [comment]
I have opened a PR [here](https://github.com/mjucker/MiMA/pull/33)
However, since it is from the ICCS fork, not this one, I don't seem to be able to link it to this issue (@dorchard).

The next step is to write some documentation, and then I will ask @lm2612 to clone and see if a) documentation can be followed, and b) MiMA can successfully be built via CMake and run on Sherlock.

**Comment by jatkinson1000** [comment]
Thi has now been transferred to a PR [here #34](https://github.com/mjucker/MiMA/pull/34) following merging of the ICCS fork with the DataWave one. The previously opened [PR #33](https://github.com/mjucker/MiMA/pull/33) will shortly be closed.

**Comment by SimonClifford** [comment]
To use the options in the CMake build, you need something like when you build the project:
```
cmake .. -DBUILD_PT_COUPLING=yes -DFTorch_DIR=<path/to/dir/containing/FTorchConfig.cmake>
```
You'll have already built fortran-pytorch-lib (the the tf-lib) and `make install`ed them somehere.
Further fixes for the fortran-pytorch-lib and tensorflow lib may get these working without the `-DFTorch_DIR ` lags

**Comment by dorchard** [comment]
https://github.com/mjucker/MiMA/pull/34 Was merged by Martin here into the home repo.
